"""Post_Photo filename not uniqe now

Revision ID: 2b27562071a0
Revises: 2ba89e01840f
Create Date: 2021-04-20 13:39:22.955067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b27562071a0'
down_revision = '2ba89e01840f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_post__photo_filename', table_name='post__photo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_post__photo_filename', 'post__photo', ['filename'], unique=1)
    # ### end Alembic commands ###
