"""New field in Post - is_done

Revision ID: 2ba89e01840f
Revises: 9f1710dd514c
Create Date: 2021-04-20 12:54:37.367116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ba89e01840f'
down_revision = '9f1710dd514c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('is_done', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'is_done')
    # ### end Alembic commands ###
