"""messages is_read

Revision ID: 53466bb654a3
Revises: d3bcf04ff7a8
Create Date: 2021-05-08 16:14:11.172159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53466bb654a3'
down_revision = 'd3bcf04ff7a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('is_read', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'is_read')
    # ### end Alembic commands ###
