"""Deleted Unknown viseters model

Revision ID: 669300273c0d
Revises: caabfb398923
Create Date: 2021-05-01 12:08:41.569483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '669300273c0d'
down_revision = 'caabfb398923'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unknown__visitor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unknown__visitor',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('post_id', sa.INTEGER(), nullable=True),
    sa.Column('photo_id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=140), nullable=True),
    sa.Column('top', sa.INTEGER(), nullable=True),
    sa.Column('right', sa.INTEGER(), nullable=True),
    sa.Column('bottom', sa.INTEGER(), nullable=True),
    sa.Column('left', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['photo_id'], ['image.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
