"""Photo is Avatars now

Revision ID: 9f1710dd514c
Revises: 086edf641673
Create Date: 2021-04-15 13:51:30.333220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f1710dd514c'
down_revision = '086edf641673'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avatar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=64), nullable=True),
    sa.Column('is_proved', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_avatar_filename'), 'avatar', ['filename'], unique=True)
    op.drop_index('ix_user__photo_filename', table_name='user__photo')
    op.drop_table('user__photo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user__photo',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('filename', sa.VARCHAR(length=64), nullable=True),
    sa.Column('is_proved', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user__photo_filename', 'user__photo', ['filename'], unique=1)
    op.drop_index(op.f('ix_avatar_filename'), table_name='avatar')
    op.drop_table('avatar')
    # ### end Alembic commands ###
