"""add Excel files to Post

Revision ID: b9aa3916063b
Revises: 84a3fbeee5ef
Create Date: 2021-05-06 14:50:25.728320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9aa3916063b'
down_revision = '84a3fbeee5ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('changed', sa.Integer(), nullable=True))
    op.add_column('post', sa.Column('excel_file_name', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'excel_file_name')
    op.drop_column('post', 'changed')
    # ### end Alembic commands ###
